# Generated by Django 3.2.9 on 2023-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='月')),
                ('total_sales', models.IntegerField(verbose_name='総売上')),
            ],
        ),
    ]
