# Generated by Django 4.2.1 on 2023-07-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_alter_payment_amount_alter_payment_due_date_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='教材の名前')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='価格')),
                ('image', models.ImageField(upload_to='materials', verbose_name='画像')),
                ('purchase_link', models.URLField(verbose_name='購入リンク')),
                ('level', models.CharField(max_length=100, verbose_name='レベル')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlySales',
        ),
    ]
