# Generated by Django 4.2.1 on 2023-07-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0023_instructor_in_person_support_and_more'),
        ('dashboard', '0002_workbook_delete_monthlysales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workbook',
            options={'verbose_name': '教材', 'verbose_name_plural': '教材一覧'},
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='アンケート名')),
                ('instructor_rating', models.PositiveIntegerField(default=3, verbose_name='講師の評価')),
                ('curriculum_rating', models.PositiveIntegerField(default=3, verbose_name='コース内容とカリキュラムの評価')),
                ('satisfaction_rating', models.PositiveIntegerField(default=3, verbose_name='授業の満足度の評価')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='その他のコメントや意見')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.instructor', verbose_name='講師名')),
            ],
            options={
                'verbose_name': 'アンケート',
                'verbose_name_plural': 'アンケート一覧',
            },
        ),
    ]
