# Generated by Django 4.2.1 on 2023-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_workbook_options_teacherevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherevaluation',
            old_name='teacher_name',
            new_name='instructor',
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='生徒ID'),
        ),
    ]
