# Generated by Django 4.2.1 on 2023-07-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_alter_payment_amount_alter_payment_due_date_and_more'),
        ('dashboard', '0004_rename_teacher_name_teacherevaluation_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='student_id',
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='生徒ID'),
        ),
    ]
