# Generated by Django 3.2.9 on 2023-05-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': '講師', 'verbose_name_plural': '講師一覧'},
        ),
    ]
