# Generated by Django 3.2.9 on 2023-05-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0002_alter_instructor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.instructor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.schedule')),
            ],
        ),
    ]
