# Generated by Django 3.2.9 on 2023-05-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0004_alter_dailyreport_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructor.schedule'),
        ),
    ]
