# Generated by Django 3.2.9 on 2023-05-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0005_alter_dailyreport_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': '日報', 'verbose_name_plural': '日報'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '講師スケジュール', 'verbose_name_plural': '講師スケジュール'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': '時間割', 'verbose_name_plural': '時間割'},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='授業内容'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(verbose_name='授業日'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructor.instructor', verbose_name='講師名'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='開始時間'),
        ),
    ]
