# Generated by Django 3.2.9 on 2023-05-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0008_alter_instructor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
