# Generated by Django 3.2.9 on 2023-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0009_delete_dailyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='available_time_slots',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='instructor',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日')], max_length=15, null=True, verbose_name='曜日'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='講師名'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('10:00~11:00', '10:00~11:00'), ('11:10~12:10', '11:10~12:10'), ('12:20~13:20', '12:20~13:20'), ('13:30~14:30', '13:30~14:30'), ('14:40~15:40', '14:40~15:40'), ('15:50~16:50', '15:50~16:50'), ('17:00~18:00', '17:00~18:00'), ('18:10~19:10', '18:10~19:10'), ('19:20~20:20', '19:20~20:20'), ('20:30~21:30', '20:30~21:30')], max_length=15, null=True, verbose_name='時間スロット'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
