# Generated by Django 3.2.9 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0010_auto_20230524_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
