# Generated by Django 3.2.9 on 2023-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0011_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='last_login',
        ),
        migrations.AddField(
            model_name='instructor',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=2, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='like',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='好きな食べ物'),
        ),
    ]
