# Generated by Django 3.2.9 on 2023-05-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0012_auto_20230526_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='講師ID'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='20210927', max_length=128, verbose_name='パスワード'),
        ),
    ]
