# Generated by Django 3.2.9 on 2023-06-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0014_auto_20230604_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
