# Generated by Django 3.2.9 on 2023-06-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0015_rename_teacher_schedule_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_id',
        ),
    ]
