# Generated by Django 3.2.9 on 2023-06-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0016_remove_instructor_instructor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='instructor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructor.instructor', verbose_name='講師名'),
        ),
    ]
