# Generated by Django 4.2.1 on 2023-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0018_remove_instructor_password_instructor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10:00~11:00', '10:00~11:00'), ('11:10~12:10', '11:10~12:10'), ('12:20~13:20', '12:20~13:20'), ('13:30~14:30', '13:30~14:30'), ('14:40~15:40', '14:40~15:40'), ('15:50~16:50', '15:50~16:50'), ('17:00~18:00', '17:00~18:00'), ('18:10~19:10', '18:10~19:10'), ('19:20~20:20', '19:20~20:20'), ('20:30~21:30', '20:30~21:30')], max_length=50, verbose_name='時間割')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.ManyToManyField(to='Instructor.timeslot'),
        ),
    ]
