# Generated by Django 4.2.1 on 2023-06-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0019_timeslot_remove_schedule_time_schedule_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': '時間割', 'verbose_name_plural': '時間割'},
        ),
    ]
