# Generated by Django 4.2.1 on 2023-06-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0020_alter_timeslot_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lesson',
        ),
    ]
