# Generated by Django 4.2.1 on 2023-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0021_remove_schedule_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.ManyToManyField(related_name='schedules', to='Instructor.timeslot'),
        ),
    ]
