# Generated by Django 4.2.1 on 2023-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0022_alter_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='in_person_support',
            field=models.BooleanField(default=False, verbose_name='対面での対応'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='online_support',
            field=models.BooleanField(default=False, verbose_name='オンライン対応'),
        ),
    ]
