# Generated by Django 4.2.4 on 2023-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0023_instructor_in_person_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='sarary',
            field=models.IntegerField(default=1200, verbose_name='時給'),
        ),
    ]
