# Generated by Django 4.2.4 on 2023-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0024_instructor_sarary'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_teacher',
            field=models.BooleanField(default=True, verbose_name='講師フラグ'),
        ),
    ]
