# Generated by Django 4.2.4 on 2023-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0025_instructor_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='sarary_m',
            field=models.IntegerField(default=0, verbose_name='月間の給料'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='sarary_y',
            field=models.IntegerField(default=0, verbose_name='年間の給料'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='sarary',
            field=models.IntegerField(default=1200, verbose_name='コマ給'),
        ),
    ]
