# Generated by Django 4.2.4 on 2023-09-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0026_instructor_sarary_m_instructor_sarary_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='sarary_m',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='sarary_y',
        ),
    ]
