# Generated by Django 4.2.4 on 2023-09-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0027_remove_instructor_sarary_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='給与の年')),
                ('amount', models.IntegerField(verbose_name='給与金額')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='給与の月')),
                ('amount', models.IntegerField(verbose_name='給与金額')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_salaries', models.ManyToManyField(to='Instructor.annualsalary', verbose_name='年間給与')),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Instructor.instructor', verbose_name='講師')),
                ('monthly_salaries', models.ManyToManyField(to='Instructor.monthlysalary', verbose_name='月間給与')),
            ],
            options={
                'verbose_name': '給与',
                'verbose_name_plural': '給与一覧',
            },
        ),
    ]
