# Generated by Django 4.2.5 on 2023-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0028_annualsalary_monthlysalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='month',
            field=models.DateField(blank=True, null=True, verbose_name='給与の月'),
        ),
    ]
