# Generated by Django 4.2.5 on 2023-09-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0030_alter_salary_annual_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='annual_salaries',
            field=models.ManyToManyField(blank=True, to='Instructor.annualsalary', verbose_name='年間給与'),
        ),
    ]
