# Generated by Django 4.2.5 on 2023-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0031_alter_salary_annual_salaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='koma',
            field=models.IntegerField(default=0, verbose_name='コマ数'),
        ),
    ]
