# Generated by Django 4.2.5 on 2023-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0032_monthlysalary_koma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='給与の月'),
        ),
    ]
