# Generated by Django 3.2.9 on 2023-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default=None, max_length=15, verbose_name='生徒名')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ふりがな（性）')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ふりがな（名）')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('grade', models.CharField(choices=[('1年', '1年'), ('2年', '2年'), ('3年', '3年')], default=None, max_length=10, verbose_name='学年')),
                ('classroom', models.CharField(choices=[('Sクラス', 'Sクラス'), ('Cクラス', 'Cクラス'), ('Gクラス', 'Gクラス'), ('Fクラス', 'Fクラス')], max_length=10, verbose_name='クラス')),
            ],
            options={
                'verbose_name': '生徒',
                'verbose_name_plural': '生徒一覧',
            },
        ),
    ]
