# Generated by Django 3.2.9 on 2023-04-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0002_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, choices=[('Sクラス', 'Sクラス'), ('Cクラス', 'Cクラス'), ('Gクラス', 'Gクラス'), ('Fクラス', 'Fクラス')], max_length=10, verbose_name='クラス'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='保護者'),
        ),
    ]
