# Generated by Django 3.2.9 on 2023-04-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20230418_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='支払い日')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('payment_status', models.CharField(choices=[('未払い', '未払い'), ('済み', '済み')], default='未払い', max_length=10, verbose_name='支払い状況')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='Student.student', verbose_name='生徒')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
