# Generated by Django 3.2.9 on 2023-04-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_attendance_tuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='欠席日')),
                ('reason', models.CharField(choices=[('病気', '病気'), ('家庭の事情', '家庭の事情'), ('その他', 'その他')], max_length=20, verbose_name='欠席理由')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('substitute_date', models.DateField(blank=True, null=True, verbose_name='振り替え日')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済みかどうか')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='生徒')),
            ],
            options={
                'verbose_name': '欠席',
                'verbose_name_plural': '欠席',
            },
        ),
    ]
