# Generated by Django 3.2.9 on 2023-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20230421_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='支払い日'),
        ),
    ]
