# Generated by Django 3.2.9 on 2023-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_auto_20230421_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
