# Generated by Django 3.2.9 on 2023-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_alter_tuition_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '支払い履歴', 'verbose_name_plural': '支払い履歴'},
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='未払い', max_length=10, verbose_name='支払い状況'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
