# Generated by Django 3.2.9 on 2023-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_auto_20230421_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('description', models.TextField(verbose_name='プロジェクトの説明')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('status', models.CharField(choices=[('ongoing', '進行中'), ('finished', '完了'), ('cancelled', '中止')], max_length=20)),
                ('members', models.ManyToManyField(blank=True, to='Student.Student', verbose_name='プロジェクトメンバー')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト一覧',
            },
        ),
    ]
