# Generated by Django 3.2.9 on 2023-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', '進行中'), ('finished', '完了'), ('cancelled', '中止')], max_length=20, verbose_name='ステータス'),
        ),
    ]
