# Generated by Django 3.2.9 on 2023-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': '入退室', 'verbose_name_plural': '入退室一覧'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
