# Generated by Django 4.2.1 on 2023-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_auto_20230526_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, choices=[('中学受験対策コース', '中学受験対策コース'), ('高校受験対策コース', '高校受験対策コース'), ('大学受験対策コース', '大学受験対策コース'), ('基礎学力集中コース', '基礎学力集中コース'), ('オーダーメイドコース', 'オーダーメイドコース'), ('パッケージプラン', 'パッケージプラン')], max_length=10, verbose_name='クラス'),
        ),
    ]
