# Generated by Django 4.2.1 on 2023-06-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_alter_student_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
