# Generated by Django 4.2.1 on 2023-06-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('1', '1枚購入 (3500円)'), ('4', '4枚購入 (14000円)'), ('8', '8枚購入 (24500円)')], max_length=2, verbose_name='回数券の種類')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='購入日')),
                ('valid_until', models.DateField(verbose_name='有効期限')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用回数')),
                ('remaining_count', models.PositiveIntegerField(default=0, verbose_name='残りの枚数')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='生徒')),
            ],
            options={
                'verbose_name': '回数券',
                'verbose_name_plural': '回数券',
            },
        ),
    ]
