# Generated by Django 4.2.1 on 2023-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='tickets',
            field=models.ManyToManyField(to='Student.ticket', verbose_name='チケットの金額'),
        ),
    ]
