# Generated by Django 4.2.1 on 2023-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_tuition_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='支払日'),
        ),
    ]
