# Generated by Django 4.2.1 on 2023-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_alter_payment_amount_alter_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='塾外生'),
        ),
    ]
