# Generated by Django 4.2.1 on 2023-07-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_student_is_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支払い日')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('payment_status', models.CharField(choices=[('未払い', '未払い'), ('済み', '済み'), ('調整中', '調整中'), ('払い戻し済み', '払い戻し済み')], default='未払い', max_length=10, verbose_name='支払い状況')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='支払い期限')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tuition', to='Student.student', verbose_name='生徒')),
            ],
        ),
    ]
