# Generated by Django 4.2.1 on 2023-07-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_external_tuition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='external_tuition',
            options={'verbose_name': '塾外生月謝', 'verbose_name_plural': '塾外生月謝'},
        ),
        migrations.AddField(
            model_name='external_tuition',
            name='tickets',
            field=models.ManyToManyField(to='Student.ticket', verbose_name='チケットの金額'),
        ),
        migrations.AlterField(
            model_name='external_tuition',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='金額'),
        ),
    ]
