# Generated by Django 4.2.4 on 2023-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_alter_external_tuition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_tuition',
            name='age_group',
            field=models.CharField(blank=True, choices=[('小学生', '小学生'), ('中学生', '中学生'), ('高校生', '高校生')], max_length=10, null=True, verbose_name='年齢グループ'),
        ),
    ]
