# Generated by Django 4.2.4 on 2023-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_tuition_initial_cost_alter_tuition_class_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='initial_cost',
        ),
        migrations.AlterField(
            model_name='tuition',
            name='class_count',
            field=models.IntegerField(choices=[(1, '週1回'), (2, '週2回')], default=1, verbose_name='週の回数'),
        ),
    ]
