# Generated by Django 4.2.4 on 2023-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0027_remove_tuition_initial_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
