# Generated by Django 4.2.4 on 2023-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0028_alter_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('未払い', '未払い'), ('済み', '済み')], default='未払い', max_length=10, verbose_name='支払い状況'),
        ),
    ]
