# Generated by Django 4.2.4 on 2023-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0029_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='to_1',
            field=models.BooleanField(default=False, verbose_name='マンツーマン'),
        ),
        migrations.AddField(
            model_name='student',
            name='to_2',
            field=models.BooleanField(default=False, verbose_name='1対2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1年', '1年'), ('2年', '2年'), ('3年', '3年'), ('4年', '4年'), ('5年', '5年'), ('6年', '6年')], default=None, max_length=10, verbose_name='学年'),
        ),
    ]
