# Generated by Django 4.2.5 on 2023-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0030_student_to_1_student_to_2_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plan',
            field=models.CharField(blank=True, choices=[('フリープラン', 'フリープラン'), ('マンツーマン', 'マンツーマン')], max_length=10, verbose_name='プラン'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(blank=True, choices=[('数学', '数学'), ('英語', '英語')], max_length=10, verbose_name='教科'),
        ),
    ]
