# Generated by Django 3.2.9 on 2023-04-17 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20230418_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ふりがな（名字）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ふりがな（名前）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='保護者名'),
        ),
    ]
