# Generated by Django 4.2.4 on 2023-08-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
