# Generated by Django 3.2.9 on 2023-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('月曜日', '月曜日'), ('火曜日', '火曜日'), ('水曜日', '水曜日'), ('木曜日', '木曜日'), ('金曜日', '金曜日'), ('土曜日', '土曜日'), ('日曜日', '日曜日')], max_length=15, null=True, verbose_name='時間スロット'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_time',
            field=models.DateTimeField(verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student_name',
            field=models.CharField(max_length=100, verbose_name='生徒名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='講師名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('10:00~11:00', '10:00~11:00'), ('11:10~12:10', '10:00~11:00'), ('12:20~13:20', '10:00~11:00'), ('13:30~14:30', '10:00~11:00'), ('14:40~15:40', '10:00~11:00'), ('15:50~16:50', '10:00~11:00'), ('17:00~18:00', '10:00~11:00'), ('18:10~19:10', '10:00~11:00'), ('19:20~20:20', '10:00~11:00'), ('20:30~21:30', '10:00~11:00')], max_length=15, null=True, verbose_name='時間スロット'),
        ),
    ]
