# Generated by Django 3.2.9 on 2023-05-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0010_auto_20230524_0146'),
        ('Reservation', '0002_auto_20230524_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '全体予約', 'verbose_name_plural': '全体予約'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.schedule'),
        ),
        migrations.AlterField(
            model_name='todaylesson',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.schedule'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
