# Generated by Django 3.2.9 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_auto_20230524_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todaylesson',
            options={'verbose_name': '本日の授業', 'verbose_name_plural': '本日の授業'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_time',
            field=models.DateField(verbose_name='予約時間'),
        ),
    ]
