# Generated by Django 3.2.9 on 2023-05-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_reservation'),
        ('Reservation', '0004_auto_20230524_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='student_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='生徒'),
        ),
    ]
