# Generated by Django 3.2.9 on 2023-05-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_auto_20230524_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodayLesson',
        ),
    ]
