# Generated by Django 4.2.1 on 2023-06-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0020_alter_timeslot_options'),
        ('Reservation', '0007_alter_reservation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructor.timeslot', verbose_name='時間帯'),
        ),
    ]
