# Generated by Django 4.2.1 on 2023-06-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0008_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255, verbose_name='授業の目標')),
                ('achievement', models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], verbose_name='達成度')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reservation.reservation')),
            ],
            options={
                'verbose_name': '日報',
                'verbose_name_plural': '日報',
            },
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
