# Generated by Django 4.2.1 on 2023-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0009_report_delete_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='achievement',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=255, verbose_name='達成度'),
        ),
    ]
