# Generated by Django 4.2.1 on 2023-06-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0010_alter_report_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Reservation.reservation'),
        ),
    ]
